@startuml

left to right direction
Actor Cliente as C

usecase "Identificarse" as I
usecase "Pagar" as P
usecase "Elegir mensajero" as EM
usecase "Confirmar" as Co
usecase "Registrarse" as R
usecase "Pagar con tarjeta" as Ptra
usecase "Pagar con transferencia" as Ptar

C -- I
C -- P
C -- EM
C -- Co

R ..> I : <<extend>>
Ptra --> P
Ptar --> P

@enduml