@startuml
'https://plantuml.com/sequence-diagram

left to right direction
Actor Usuario as U
Actor Administrador as A


usecase "Iniciar Sesion" as IS
usecase "Recuperar contraseña" as RC
usecase "Modificar contraseña" as MC
usecase "Cerrar Sesion" as CS
usecase "Registrar Usuario" as RU
usecase "Instalar programa" as IP

U <|- A
U -- IS
U -- RC
U -- MC
U -- CS
A -- RU
A -- IP



@enduml